### PR TITLE
fish completion

### PR DESCRIPTION
**Pull request by LChris314**
Adds completion for fish shell. The completion file is based on the pacaur one and modified for aurman.

### CODE REVIEW

**Comment by polygamma** [comment]
Thank you very much!
I am going to take a closer look tomorrow, and will very likely merge it then.

**Comment by polygamma** [comment]
Sorry, I am currently very busy with university stuff - I have not forgotten about this PR

**Comment by Mauladen** [comment]
I am using zsh and so there is no way to test this PR

**Comment by LChris314** [comment]
I'm sorry but as you can see I deleted my fork by mistake, and at the moment I don't have the forked repo locally available to me. I've just made a new fork and I can do the same commit again, but I think that means a new PR is needed. Again, I apologise - it's a silly oversight for me to delete the fork when it's still needed.

**Comment by polygamma** [comment]
A new PR would be very welcome! Thank you very much

**Comment by LChris314** [comment]
New PR is out, closing this one.

**Pull request closed without merging**
